package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCoinRecords;
import org.linlinjava.litemall.db.domain.LitemallCoinRecordsExample;

public interface LitemallCoinRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    long countByExample(LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int insert(LitemallCoinRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCoinRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    LitemallCoinRecords selectOneByExample(LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    LitemallCoinRecords selectOneByExampleSelective(@Param("example") LitemallCoinRecordsExample example, @Param("selective") LitemallCoinRecords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    List<LitemallCoinRecords> selectByExampleSelective(@Param("example") LitemallCoinRecordsExample example, @Param("selective") LitemallCoinRecords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    List<LitemallCoinRecords> selectByExample(LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    LitemallCoinRecords selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCoinRecords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    LitemallCoinRecords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    LitemallCoinRecords selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCoinRecords record, @Param("example") LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCoinRecords record, @Param("example") LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCoinRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCoinRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallCoinRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_records
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}