package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPlatformAccount;
import org.linlinjava.litemall.db.domain.LitemallPlatformAccountExample;

public interface LitemallPlatformAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    long countByExample(LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int insert(LitemallPlatformAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPlatformAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    LitemallPlatformAccount selectOneByExample(LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    LitemallPlatformAccount selectOneByExampleSelective(@Param("example") LitemallPlatformAccountExample example, @Param("selective") LitemallPlatformAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    List<LitemallPlatformAccount> selectByExampleSelective(@Param("example") LitemallPlatformAccountExample example, @Param("selective") LitemallPlatformAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    List<LitemallPlatformAccount> selectByExample(LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    LitemallPlatformAccount selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPlatformAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    LitemallPlatformAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    LitemallPlatformAccount selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPlatformAccount record, @Param("example") LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPlatformAccount record, @Param("example") LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPlatformAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPlatformAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPlatformAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}