package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCoinAccount;
import org.linlinjava.litemall.db.domain.LitemallCoinAccountExample;

public interface LitemallCoinAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    long countByExample(LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int insert(LitemallCoinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCoinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    LitemallCoinAccount selectOneByExample(LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    LitemallCoinAccount selectOneByExampleSelective(@Param("example") LitemallCoinAccountExample example, @Param("selective") LitemallCoinAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    List<LitemallCoinAccount> selectByExampleSelective(@Param("example") LitemallCoinAccountExample example, @Param("selective") LitemallCoinAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    List<LitemallCoinAccount> selectByExample(LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    LitemallCoinAccount selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCoinAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    LitemallCoinAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    LitemallCoinAccount selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCoinAccount record, @Param("example") LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCoinAccount record, @Param("example") LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCoinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCoinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallCoinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coin_account
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}