package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPlatformTransactions;
import org.linlinjava.litemall.db.domain.LitemallPlatformTransactionsExample;

public interface LitemallPlatformTransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    long countByExample(LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int insert(LitemallPlatformTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPlatformTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    LitemallPlatformTransactions selectOneByExample(LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    LitemallPlatformTransactions selectOneByExampleSelective(@Param("example") LitemallPlatformTransactionsExample example, @Param("selective") LitemallPlatformTransactions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    List<LitemallPlatformTransactions> selectByExampleSelective(@Param("example") LitemallPlatformTransactionsExample example, @Param("selective") LitemallPlatformTransactions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    List<LitemallPlatformTransactions> selectByExample(LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    LitemallPlatformTransactions selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPlatformTransactions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    LitemallPlatformTransactions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    LitemallPlatformTransactions selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPlatformTransactions record, @Param("example") LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPlatformTransactions record, @Param("example") LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPlatformTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPlatformTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPlatformTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_transactions
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}