package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPlatform;
import org.linlinjava.litemall.db.domain.LitemallPlatformExample;

public interface LitemallPlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    long countByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int insert(LitemallPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    LitemallPlatform selectOneByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    LitemallPlatform selectOneByExampleSelective(@Param("example") LitemallPlatformExample example, @Param("selective") LitemallPlatform.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    List<LitemallPlatform> selectByExampleSelective(@Param("example") LitemallPlatformExample example, @Param("selective") LitemallPlatform.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    List<LitemallPlatform> selectByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    LitemallPlatform selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPlatform.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    LitemallPlatform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    LitemallPlatform selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPlatform record, @Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPlatform record, @Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}