package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallPlatformAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    public static final Byte IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    public static final Byte NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.platfrom_id
     *
     * @mbg.generated
     */
    private Integer platfromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.idcard_number
     *
     * @mbg.generated
     */
    private String idcardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.available_amount
     *
     * @mbg.generated
     */
    private Integer availableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.unavailable_amount
     *
     * @mbg.generated
     */
    private Integer unavailableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.used_amuont
     *
     * @mbg.generated
     */
    private Integer usedAmuont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.total_amount
     *
     * @mbg.generated
     */
    private Integer totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform_account.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.id
     *
     * @return the value of litemall_platform_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.id
     *
     * @param id the value for litemall_platform_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.platfrom_id
     *
     * @return the value of litemall_platform_account.platfrom_id
     *
     * @mbg.generated
     */
    public Integer getPlatfromId() {
        return platfromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.platfrom_id
     *
     * @param platfromId the value for litemall_platform_account.platfrom_id
     *
     * @mbg.generated
     */
    public void setPlatfromId(Integer platfromId) {
        this.platfromId = platfromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.mobile
     *
     * @return the value of litemall_platform_account.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.mobile
     *
     * @param mobile the value for litemall_platform_account.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.real_name
     *
     * @return the value of litemall_platform_account.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.real_name
     *
     * @param realName the value for litemall_platform_account.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.idcard_number
     *
     * @return the value of litemall_platform_account.idcard_number
     *
     * @mbg.generated
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.idcard_number
     *
     * @param idcardNumber the value for litemall_platform_account.idcard_number
     *
     * @mbg.generated
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.user_id
     *
     * @return the value of litemall_platform_account.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.user_id
     *
     * @param userId the value for litemall_platform_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.version
     *
     * @return the value of litemall_platform_account.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.version
     *
     * @param version the value for litemall_platform_account.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.available_amount
     *
     * @return the value of litemall_platform_account.available_amount
     *
     * @mbg.generated
     */
    public Integer getAvailableAmount() {
        return availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.available_amount
     *
     * @param availableAmount the value for litemall_platform_account.available_amount
     *
     * @mbg.generated
     */
    public void setAvailableAmount(Integer availableAmount) {
        this.availableAmount = availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.unavailable_amount
     *
     * @return the value of litemall_platform_account.unavailable_amount
     *
     * @mbg.generated
     */
    public Integer getUnavailableAmount() {
        return unavailableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.unavailable_amount
     *
     * @param unavailableAmount the value for litemall_platform_account.unavailable_amount
     *
     * @mbg.generated
     */
    public void setUnavailableAmount(Integer unavailableAmount) {
        this.unavailableAmount = unavailableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.used_amuont
     *
     * @return the value of litemall_platform_account.used_amuont
     *
     * @mbg.generated
     */
    public Integer getUsedAmuont() {
        return usedAmuont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.used_amuont
     *
     * @param usedAmuont the value for litemall_platform_account.used_amuont
     *
     * @mbg.generated
     */
    public void setUsedAmuont(Integer usedAmuont) {
        this.usedAmuont = usedAmuont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.total_amount
     *
     * @return the value of litemall_platform_account.total_amount
     *
     * @mbg.generated
     */
    public Integer getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.total_amount
     *
     * @param totalAmount the value for litemall_platform_account.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.status
     *
     * @return the value of litemall_platform_account.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.status
     *
     * @param status the value for litemall_platform_account.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.add_time
     *
     * @return the value of litemall_platform_account.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.add_time
     *
     * @param addTime the value for litemall_platform_account.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.update_time
     *
     * @return the value of litemall_platform_account.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.update_time
     *
     * @param updateTime the value for litemall_platform_account.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform_account.deleted
     *
     * @return the value of litemall_platform_account.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform_account.deleted
     *
     * @param deleted the value for litemall_platform_account.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", platfromId=").append(platfromId);
        sb.append(", mobile=").append(mobile);
        sb.append(", realName=").append(realName);
        sb.append(", idcardNumber=").append(idcardNumber);
        sb.append(", userId=").append(userId);
        sb.append(", version=").append(version);
        sb.append(", availableAmount=").append(availableAmount);
        sb.append(", unavailableAmount=").append(unavailableAmount);
        sb.append(", usedAmuont=").append(usedAmuont);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", status=").append(status);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallPlatformAccount other = (LitemallPlatformAccount) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPlatfromId() == null ? other.getPlatfromId() == null : this.getPlatfromId().equals(other.getPlatfromId()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getIdcardNumber() == null ? other.getIdcardNumber() == null : this.getIdcardNumber().equals(other.getIdcardNumber()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getAvailableAmount() == null ? other.getAvailableAmount() == null : this.getAvailableAmount().equals(other.getAvailableAmount()))
            && (this.getUnavailableAmount() == null ? other.getUnavailableAmount() == null : this.getUnavailableAmount().equals(other.getUnavailableAmount()))
            && (this.getUsedAmuont() == null ? other.getUsedAmuont() == null : this.getUsedAmuont().equals(other.getUsedAmuont()))
            && (this.getTotalAmount() == null ? other.getTotalAmount() == null : this.getTotalAmount().equals(other.getTotalAmount()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPlatfromId() == null) ? 0 : getPlatfromId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getIdcardNumber() == null) ? 0 : getIdcardNumber().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getAvailableAmount() == null) ? 0 : getAvailableAmount().hashCode());
        result = prime * result + ((getUnavailableAmount() == null) ? 0 : getUnavailableAmount().hashCode());
        result = prime * result + ((getUsedAmuont() == null) ? 0 : getUsedAmuont().hashCode());
        result = prime * result + ((getTotalAmount() == null) ? 0 : getTotalAmount().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Byte("0"), "未删除"),
        IS_DELETED(new Byte("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private final Byte value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        Deleted(Byte value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public Byte getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public Byte value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_platform_account
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        platfromId("platfrom_id", "platfromId", "INTEGER", false),
        mobile("mobile", "mobile", "VARCHAR", false),
        realName("real_name", "realName", "VARCHAR", false),
        idcardNumber("idcard_number", "idcardNumber", "VARCHAR", false),
        userId("user_id", "userId", "INTEGER", false),
        version("version", "version", "INTEGER", false),
        availableAmount("available_amount", "availableAmount", "INTEGER", false),
        unavailableAmount("unavailable_amount", "unavailableAmount", "INTEGER", false),
        usedAmuont("used_amuont", "usedAmuont", "INTEGER", false),
        totalAmount("total_amount", "totalAmount", "INTEGER", false),
        status("status", "status", "BIT", true),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "TINYINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform_account
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}